name: "Tweak Settings Workflow"

settings:
  typing_speed: 0.04
  command_delay: 1.5
  initial_delay: 3.0
  clear_screen: false
  cols: 120
  rows: 48

templates:
  # Navigation
  - &enter_key
    text: ""

commands:

  #  Start phantom-wg CLI
  - text: "phantom-wg"

  #  Tweak Settings Flow
  - text: "1"
  - text: "7"
  - text: "1"
  - text: "y"
  - *enter_key
  - text: "1"
  - text: "y"
  - *enter_key